"""1

Revision ID: 58c4ef4ee4ff
Revises: f6a5d7b8c9e0
Create Date: 2026-05-29 16:02:23.827191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58c4ef4ee4ff'
down_revision: Union[str, None] = 'f6a5d7b8c9e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('datasets', 'processing_status',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='预处理状态: pending/processing/completed/failed',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_constraint('federated_participants_task_id_fkey', 'federated_participants', type_='foreignkey')
    op.create_foreign_key(None, 'federated_participants', 'federated_tasks', ['task_id'], ['id'])
    op.alter_column('federated_tasks', 'dp_epsilon',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'8'::double precision"))
    op.alter_column('federated_tasks', 'dp_delta',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'1e-05'::double precision"))
    op.alter_column('federated_tasks', 'dp_noise_multiplier',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'1.1'::double precision"))
    op.alter_column('federated_tasks', 'dp_max_grad_norm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'1'::double precision"))
    op.alter_column('federated_tasks', 'celery_task_id',
               existing_type=sa.VARCHAR(length=128),
               comment='Celery AsyncResult.id for the federated training task',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('federated_tasks', 'celery_task_id',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='Celery AsyncResult.id for the federated training task',
               existing_nullable=True)
    op.alter_column('federated_tasks', 'dp_max_grad_norm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'1'::double precision"))
    op.alter_column('federated_tasks', 'dp_noise_multiplier',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'1.1'::double precision"))
    op.alter_column('federated_tasks', 'dp_delta',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'1e-05'::double precision"))
    op.alter_column('federated_tasks', 'dp_epsilon',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'8'::double precision"))
    op.drop_constraint(None, 'federated_participants', type_='foreignkey')
    op.create_foreign_key('federated_participants_task_id_fkey', 'federated_participants', 'federated_tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.alter_column('datasets', 'processing_status',
               existing_type=sa.VARCHAR(length=32),
               comment='预处理状态: pending/processing/completed/failed',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    # ### end Alembic commands ###
